"""Auto-generated obfuscated module. Source: visagate/__init__.py
Regenerated by scripts/obfuscate.py -- do not edit by hand."""
import base64, zlib
_K = bytes.fromhex("168962716156c5fc078ebcda3d945040")
_DATA = "blNvudpYB8wLi2znYuW1/QfLzn1RZ7GailJczLaEGzlGe5UBpxWBi6oyzclx9IwsaQXLx/BS7rtGQXU4Nik5kiA5OLANzfN1SNI3wEvNcv89pYEjn2+uEljB+BS4ZMESw/tqSeJYOxRIasI9GLHH"
_raw = base64.b64decode(_DATA)
_dec = bytes(b ^ _K[i % len(_K)] for i, b in enumerate(_raw))
_src = zlib.decompress(_dec)
exec(compile(_src, "visagate/__init__.py", "exec"), globals())
